/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadc",
        "background": "#f8f9fb",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#49d7f4",
        "on-surface-variant": "#3c494c",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#920021",
        "surface-bright": "#f8f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5a5f65",
        "outline": "#6c797d",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-tint": "#006879",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#00444f",
        "on-tertiary-fixed": "#400009",
        "error-container": "#ffdad6",
        "outline-variant": "#bbc9cd",
        "primary": "#006879",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary": "#b62034",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed-dim": "#ffb3b3",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#5e6369",
        "on-secondary-fixed": "#171c21",
        "secondary-fixed": "#dee3e9",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#ffdad9",
        "on-error": "#ffffff",
        "on-tertiary-container": "#80001b",
        "primary-fixed": "#a8edff",
        "primary-container": "#00b8d4",
        "surface": "#f8f9fb",
        "on-primary-fixed-variant": "#004e5b",
        "inverse-primary": "#49d7f4",
        "surface-container": "#eceef0",
        "tertiary-container": "#ff8285",
        "secondary-fixed-dim": "#c2c7cd",
        "secondary-container": "#dce0e7",
        "on-secondary-fixed-variant": "#42474d"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Sans KR", "sans-serif"],
        body: ["Noto Sans KR", "sans-serif"],
        label: ["Noto Sans KR", "sans-serif"]
      }
    },
  },
  plugins: [],
}
